CREATE TABLE bjr_users
(
UserID INT NOT NULL AUTO_INCREMENT,
UserEmail VARCHAR(255) NOT NULL,
UserName VARCHAR(255) NOT NULL,
UserLastName VARCHAR(255),
UserFirstName VARCHAR(255),
UserGender VARCHAR(16),
UserInterest VARCHAR(255),
UserLocation VARCHAR(255),
UserLastLoginIP VARCHAR(255),
UserLastActiveTime DATE
);